# Generated by Django 3.1.6 on 2021-03-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hope_app', '0004_auto_20210309_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='volunteer_experience',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hope_app.portfolio'),
        ),
    ]
