# Generated by Django 3.1.6 on 2021-03-09 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hope_app', '0005_auto_20210309_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerexperience',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hope_app.portfolio'),
        ),
    ]
