# Generated by Django 3.1.6 on 2021-03-12 06:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hope_app', '0009_auto_20210312_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 6, 51, 47, 690042, tzinfo=utc)),
        ),
    ]
